#!/usr/bin/env python3
"""Generate ApolloThemeGalleryCatalog.gen.{h,m} from theme-gallery/themes/*.json.

Each JSON file must match Theme Builder export shape (apolloThemeBuilder, name,
colors). Slug is the filename without .json. Output is compiled into the tweak
dylib — no runtime filesystem reads.
"""
from __future__ import annotations

import json
import os
import re
import sys

VALID_ROLES = (
    "accent",
    "primaryBG",
    "secondaryBG",
    "tertiaryBG",
    "separator",
    "bar",
    "gray",
    "text",
)
VALID_MODES = ("light", "dark")
NAME_MAX_LENGTH = 60


def escape_c_string(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def normalize_hex(value: object) -> str | None:
    if not isinstance(value, str):
        return None
    clean = value.strip().replace("#", "")
    if len(clean) != 6:
        return None
    if not re.fullmatch(r"[0-9a-fA-F]{6}", clean):
        return None
    return clean.upper()


def sanitize_colors(raw: object) -> dict[str, str]:
    if not isinstance(raw, dict):
        return {}
    valid_keys = {f"{role}.{mode}" for role in VALID_ROLES for mode in VALID_MODES}
    out: dict[str, str] = {}
    for key, value in raw.items():
        if not isinstance(key, str) or key not in valid_keys:
            continue
        hex_value = normalize_hex(value)
        if hex_value:
            out[key] = hex_value
    return out


def clamp_name(name: object, fallback: str) -> str:
    if not isinstance(name, str):
        return fallback
    trimmed = name.strip()
    if not trimmed:
        return fallback
    if len(trimmed) > NAME_MAX_LENGTH:
        trimmed = trimmed[:NAME_MAX_LENGTH]
    return trimmed


def load_themes(themes_dir: str) -> list[dict]:
    entries: list[dict] = []
    for filename in sorted(os.listdir(themes_dir)):
        if not filename.endswith(".json"):
            continue
        path = os.path.join(themes_dir, filename)
        with open(path, encoding="utf-8") as fp:
            data = json.load(fp)
        if not isinstance(data, dict):
            print(f"skip {filename}: root is not an object", file=sys.stderr)
            continue
        colors_source = data.get("colors") if isinstance(data.get("colors"), dict) else data
        colors = sanitize_colors(colors_source)
        has_marker = data.get("apolloThemeBuilder") is not None
        if not colors and not has_marker:
            print(f"skip {filename}: no valid colors", file=sys.stderr)
            continue
        slug = filename[:-5]
        name = clamp_name(data.get("name"), slug.replace("-", " ").title())
        entries.append({"slug": slug, "name": name, "colors": colors})
    entries.sort(key=lambda item: item["name"].casefold())
    return entries


def emit_colors_dict(colors: dict[str, str], indent: str) -> list[str]:
    lines = [f"{indent}@{{"]
    for key in sorted(colors.keys()):
        lines.append(f'{indent}    @"{escape_c_string(key)}": @"{escape_c_string(colors[key])}",')
    lines.append(f"{indent}}}")
    return lines


def emit_source(themes: list[dict], out_m: str) -> None:
  lines = [
      '// Generated by theme-gallery/scripts/generate_catalog.py — do not edit.',
      '#import "ApolloThemeGalleryCatalog.gen.h"',
      '',
      'NSArray<NSDictionary *> *ApolloThemeGalleryCatalogThemes(void) {',
      '    static NSArray<NSDictionary *> *catalog;',
      '    static dispatch_once_t onceToken;',
      '    dispatch_once(&onceToken, ^{',
      '        catalog = @[',
  ]
  for theme in themes:
      lines.append('            @{')
      lines.append(f'                @"slug": @"{escape_c_string(theme["slug"])}",')
      lines.append(f'                @"name": @"{escape_c_string(theme["name"])}",')
      lines.append('                @"colors": ')
      lines.extend(emit_colors_dict(theme["colors"], "                "))
      lines.append('            },')
  lines.extend([
      '        ];',
      '    });',
      '    return catalog;',
      '}',
      '',
  ])
  with open(out_m, "w", encoding="utf-8") as fp:
      fp.write("\n".join(lines))


def emit_header(out_h: str) -> None:
    content = """// Generated by theme-gallery/scripts/generate_catalog.py — do not edit.
#import <Foundation/Foundation.h>

__BEGIN_DECLS
// Bundled gallery themes: slug, name, colors (role.mode -> RRGGBB hex).
NSArray<NSDictionary *> *ApolloThemeGalleryCatalogThemes(void);
__END_DECLS
"""
    with open(out_h, "w", encoding="utf-8") as fp:
        fp.write(content)


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: generate_catalog.py <output_dir>", file=sys.stderr)
        return 1
    out_dir = sys.argv[1]
    script_dir = os.path.dirname(os.path.abspath(__file__))
    themes_dir = os.path.join(script_dir, "..", "themes")
    themes = load_themes(themes_dir)
    if not themes:
        print(f"no themes found in {themes_dir}", file=sys.stderr)
        return 1
    os.makedirs(out_dir, exist_ok=True)
    emit_header(os.path.join(out_dir, "ApolloThemeGalleryCatalog.gen.h"))
    emit_source(themes, os.path.join(out_dir, "ApolloThemeGalleryCatalog.gen.m"))
    print(f"Wrote {len(themes)} themes to {out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
